version: "2"
run:
  issues-exit-code: 1
  tests: false
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - gocritic
    - goprintffuncname
    - govet
    - ineffassign
    - makezero
    - misspell
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    forbidigo:
      forbid:
        - pattern: ^fmt\.Errorf$
  exclusions:
    generated: lax
    rules:
      - path: (.+)\.go$
        text: Error return value of .((os.)?std(out|err)..*|.*Close|.*Seek|.*Flush|os.Remove(All)?|.*print(f|ln)?|os.(Un)?Setenv). is not check
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  fix: false
formatters:
  settings:
    goimports:
      local-prefixes:
        - github.com/fumiama/go-docx
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
